set autonumber true
set time_height 30
set column_width 150

participant Manufacturer as Manufacturer
participant Transfer Agent as TransferAgent
participant Device as Device
participant Introducer as Introducer
participant User as User
participant Controller as Controller
 
Manufacturer-->Device: TaURL, DevURN, OTP, secret 
Manufacturer-->TransferAgent: DevURN, OTP

Device-->Introducer: QR with TaURL, DevID, OTP, secret

Introducer->TransferAgent: DevID

User-->Introducer: ContURL, DevLabel

Introducer->TransferAgent: DevID, OTP, ContURL

Introducer->Controller: DevURN, secret, DevLabel


Device->TransferAgent: DevURN
TransferAgent->Device: ContURL encrpted with OTP

Device->Controller: Hello authenticated with secret
Controller->Device: HelloAck authenticated with secret
