set autonumber true
set time_height 30
set column_width 150

#participant Manufacturer as Manufacturer

participant Transfer Agent as TransferAgent
participant Device as Device
participant Introducer as Introducer
#participant User as User
participant Controller as Controller
 
#Manufacturer-->Device: TaURL, DevURN, OTP, secret 
#Manufacturer-->TransferAgent: DevURN, OTP

Device-->Introducer: QR with TaURL, DevURN, OTP, secret

Introducer->TransferAgent: Get UI ( DevURN )

#User-->Introducer: Provide ContURL and DevLabel

Introducer->TransferAgent: bind( DevURN, OTP, ContURL )

Introducer->Controller: add( DevURN, DevSecret, DevLabel )


Device->TransferAgent: findController( DevURN )
TransferAgent->Device: ContURL encrpted with OTP

Device->Controller: Hello authenticated with DevSecret
Controller->Device: HelloAck authenticated with DevSecret

